services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - $PG_PORT:$PG_PORT
    volumes:
      - pgdata:/var/lib/postgres/data

  backend:
    depends_on:
      - postgres
    build: ./server
    restart: always
    develop:
      watch:
        - action: sync
          path: server
          target: server
    ports:
      - $BACKEND_PORT:$BACKEND_PORT

  app:
    depends_on:
      - backend
    build: ./
    restart: always
    environment:
      BACKEND_PORT: $BACKEND_PORT
    develop:
      watch:
        - action: sync
          path: app
          target: /basethree/app
          ignore:
            - node_modules/
    ports:
      - $NODE_PORT:$NODE_PORT

volumes:
  pgdata:
